[package]
name = "seismic_refatoring"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rppal = "0.19.0"
linux-embedded-hal = "0.4.0"
embedded-graphics = "0.8.1"
machine-ip = "0.2.1"
ssd1306 = "0.9.0"
